// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockScreener.Infrastructure.Persistence;

#nullable disable

namespace StockScreener.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510174038_CheckSchema")]
    partial class CheckSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockScreener.Domain.Entities.FilterPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FilterPresets_UserId");

                    b.ToTable("FilterPresets", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.Fundamentals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CurrentRatio")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("DebtToEquity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EPSGrowth")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateOnly?>("ExDividendDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FiscalYearEnd")
                        .HasColumnType("date");

                    b.Property<decimal?>("GrossMargin")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("OperatingMargin")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("PB_Ratio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PE_Ratio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PS_Ratio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ProfitMargin")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("QuickRatio")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("ROE")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("RevenueGrowth")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("TotalEquity")
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique()
                        .HasDatabaseName("IX_Fundamentals_StockId");

                    b.ToTable("Fundamentals", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "TradeDate")
                        .HasDatabaseName("IX_PriceHistory_StockId_Date");

                    b.ToTable("PriceHistory", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("AvgVolume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Beta")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("DayHigh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("DayLow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Week52Low")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("IX_Stocks_Symbol");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.TechnicalIndicators", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ATR_14")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("AvgVolume_20")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("BB_Lower")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BB_Middle")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BB_Upper")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MACD")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MACD_Histogram")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MACD_Signal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RSI_14")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("SMA_20")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SMA_200")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SMA_50")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "TradeDate")
                        .HasDatabaseName("IX_TechnicalIndicators_StockId_Date");

                    b.ToTable("TechnicalIndicators", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Watchlists_UserId");

                    b.ToTable("Watchlists", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CostBasis")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SharesOwned")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("WatchlistId", "StockId")
                        .IsUnique()
                        .HasDatabaseName("IX_WatchlistItems_WatchlistId_StockId");

                    b.ToTable("WatchlistItems", (string)null);
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.Fundamentals", b =>
                {
                    b.HasOne("StockScreener.Domain.Entities.Stock", "Stock")
                        .WithOne("Fundamentals")
                        .HasForeignKey("StockScreener.Domain.Entities.Fundamentals", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("StockScreener.Domain.Entities.Stock", "Stock")
                        .WithMany("PriceHistory")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.TechnicalIndicators", b =>
                {
                    b.HasOne("StockScreener.Domain.Entities.Stock", "Stock")
                        .WithMany("TechnicalIndicators")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("StockScreener.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockScreener.Domain.Entities.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.Stock", b =>
                {
                    b.Navigation("Fundamentals");

                    b.Navigation("PriceHistory");

                    b.Navigation("TechnicalIndicators");
                });

            modelBuilder.Entity("StockScreener.Domain.Entities.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
